cd "/Users/annasmetanina/Library/Mobile Documents/com~apple~CloudDocs/EconomicsMA_HunterCollege/ECO 722 Nonlinear Econometric Analysis/HPSA Project"
capture log close AS
log using ranked_list.log, name(AS) replace

clear
input str80 med_sch ranked_school
"UNIVERSITY OF WASHINGTON" 1
"UNIVERSITY OF NORTH CAROLINA—CHAPEL HILL" 1
"UNIVERSITY OF CALIFORNIA—SAN FRANCISCO" 1
"OREGON HEALTH AND SCIENCE UNIVERSITY" 1
"UNIVERSITY OF MINNESOTA" 1
"UNIVERSITY OF NEBRASKA MEDICAL CENTER" 1
"UNIVERSITY OF MICHIGAN—ANN ARBOR" 1
"UNIVERSITY OF MASSACHUSETTS" 1
"UNIVERSITY OF WISCONSIN—MADISON" 1
"UNIVERSITY OF NEW MEXICO" 1
"UNIVERSITY OF COLORADO" 1
"UNIVERSITY OF IOWA (CARVER)" 1
"UNIVERSITY OF CALIFORNIA—DAVIS" 1
"UNIVERSITY OF KANSAS MEDICAL CENTER" 1
"UNIVERSITY OF ALABAMA—BIRMINGHAM" 1
"UNIVERSITY OF ROCHESTER" 1
"BAYLOR COLLEGE OF MEDICINE" 1
"UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER—SAN ANTONIO" 1
"UNIVERSITY OF VERMONT" 1
"OHIO STATE UNIVERSITY" 1
"MICHIGAN STATE UNIVERSITY" 1
"UNIVERSITY OF UTAH" 1
"INDIANA UNIVERSITY" 1
"UNIVERSITY OF PITTSBURGH" 1
"UNIVERSITY OF MISSOURI" 1
"UNIVERSITY OF FLORIDA" 1
"UNIVERSITY OF VIRGINIA" 1
"BOSTON UNIVERSITY" 1
"UNIVERSITY OF ILLINOIS" 1
"UNIVERSITY OF KENTUCKY" 1
end

replace med_sch = "UNIVERSITY OF WASHINGTON SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF WASHINGTON"

replace med_sch = "UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF NORTH CAROLINA—CHAPEL HILL"

replace med_sch = "UNIVERSITY OF CALIFORNIA, SAN FRANCISCO" ///
    if med_sch == "UNIVERSITY OF CALIFORNIA—SAN FRANCISCO"

replace med_sch = "OREGON HEALTH SCIENCES UNIVERSITY SCHOOL OF MEDICINE" ///
    if med_sch == "OREGON HEALTH AND SCIENCE UNIVERSITY"

replace med_sch = "UNIVERSITY OF MINNESOTA MEDICAL SCHOOL" ///
    if med_sch == "UNIVERSITY OF MINNESOTA"

replace med_sch = "UNIVERSITY OF NEBRASKA COLLEGE OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF NEBRASKA MEDICAL CENTER"

replace med_sch = "UNIVERSITY OF MICHIGAN MEDICAL SCHOOL" ///
    if med_sch == "UNIVERSITY OF MICHIGAN—ANN ARBOR"

replace med_sch = "UNIVERSITY OF MASSACHUSETTS MEDICAL SCHOOL" ///
    if med_sch == "UNIVERSITY OF MASSACHUSETTS"

replace med_sch = "UNIVERSITY OF WISCONSIN SCHOOL OF MEDICINE AND PUBLIC HEALTH" ///
    if med_sch == "UNIVERSITY OF WISCONSIN—MADISON"

replace med_sch = "UNIVERSITY OF NEW MEXICO SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF NEW MEXICO"

replace med_sch = "UNIVERSITY OF COLORADO SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF COLORADO"

replace med_sch = "UNIVERSITY OF IOWA, RJ & L CARVER COLLEGE OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF IOWA (CARVER)"

replace med_sch = "UNIVERSITY OF CALIFORNIA, DAVIS SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF CALIFORNIA—DAVIS"

replace med_sch = "UNIVERSITY OF KANSAS SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF KANSAS MEDICAL CENTER"

replace med_sch = "UNIVERSITY OF ALABAMA SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF ALABAMA—BIRMINGHAM"

replace med_sch = "UNIVERSITY OF ROCHESTER SCHOOL OF MEDICINE AND DENTISTRY" ///
    if med_sch == "UNIVERSITY OF ROCHESTER"

replace med_sch = "BAYLOR COLLEGE OF MEDICINE" ///
    if med_sch == "BAYLOR COLLEGE OF MEDICINE"

replace med_sch = "UNIVERSITY OF TEXAS MEDICAL SCHOOL AT SAN ANTONIO" ///
    if med_sch == "UNIVERSITY OF TEXAS HEALTH SCIENCE CENTER—SAN ANTONIO"

replace med_sch = "UNIVERSITY OF VERMONT COLLEGE OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF VERMONT"

replace med_sch = "OHIO STATE UNIVERSITY COLLEGE OF MEDICINE" ///
    if med_sch == "OHIO STATE UNIVERSITY"

replace med_sch = "MICHIGAN STATE UNIVERSITY COLLEGE OF HUMAN MEDICINE" ///
    if med_sch == "MICHIGAN STATE UNIVERSITY"

replace med_sch = "UNIVERSITY OF UTAH SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF UTAH"

replace med_sch = "INDIANA UNIVERSITY SCHOOL OF MEDICINE" ///
    if med_sch == "INDIANA UNIVERSITY"

replace med_sch = "UNIVERSITY OF PITTSBURGH SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF PITTSBURGH"

replace med_sch = "UNIVERSITY OF MISSOURI SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF MISSOURI"

replace med_sch = "UNIVERSITY OF FLORIDA COLLEGE OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF FLORIDA"

replace med_sch = "UNIVERSITY OF VIRGINIA SCHOOL OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF VIRGINIA"

replace med_sch = "BOSTON UNIVERSITY SCHOOL OF MEDICINE" ///
    if med_sch == "BOSTON UNIVERSITY"

replace med_sch = "UNIVERSITY OF ILLINOIS COLLEGE OF MED (CHI/PEO/ROC)" ///
    if med_sch == "UNIVERSITY OF ILLINOIS"

replace med_sch = "UNIVERSITY OF KENTUCKY COLLEGE OF MEDICINE" ///
    if med_sch == "UNIVERSITY OF KENTUCKY"

replace med_sch = trim(upper(med_sch))

save ranked_list.dta, replace

log close AS
